spring:
  config:
    import: classpath:application-kafka.yml
  kafka:
    bootstrap-servers: kafka:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
