apply plugin: 'com.github.spotbugs'

spotbugs {
	toolVersion = '4.10.4'
	effort = rootProject.spotbugsEffort
	reportLevel = rootProject.spotbugsReportLevel
}

tasks.matching {task -> task.name.startsWith('spotbugs')}.configureEach {
	reports {
		html {
			required = true
		}
		xml {
			required = false
		}
	}
}

dependencies {
	spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.14.0'
}
