apply from: rootProject.file('tooling/quality/spotbugs/spotbugs.gradle')
apply from: rootProject.file('tooling/quality/checkstyle/checkstyle.gradle')
apply from: rootProject.file('tooling/quality/jacoco/jacoco.gradle')
apply from: rootProject.file('tooling/quality/spotless/spotless-java.gradle')
apply from: rootProject.file('tooling/quality/dependencycheck/dependencycheck.gradle')
apply from: rootProject.file('tooling/quality/pmd/pmd.gradle')
dependencies {

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    implementation project(':adapter:common')
    implementation project(':domain')

    implementation 'com.google.code.gson:gson'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.apache.camel.springboot:camel-spring-boot-starter'
    implementation 'org.apache.camel.springboot:camel-file-starter'
    testImplementation project(path: ':adapter:common', configuration: 'testArtifacts')
}

rootProject.configureTestDependencies(project)
