#!/usr/bin/env python3
"""Deterministic inventory of documented and executable Agentic SDD specifications."""

from __future__ import annotations

import argparse
import difflib
import pathlib
import re
import sys
from dataclasses import dataclass

STATUS_RE = re.compile(r"^Status:\s*(.+?)\s*$", re.MULTILINE)


@dataclass(frozen=True)
class FeatureInventory:
    feature: str
    status: str
    has_spec: bool
    has_plan: bool
    has_tasks: bool

    @property
    def harness_mode(self) -> str:
        return "executable" if self.has_tasks else "document-only"

    @property
    def validate_all(self) -> str:
        return "selected" if self.has_tasks else "not selected"


def declared_status(spec_path: pathlib.Path) -> str:
    if not spec_path.is_file():
        return "MISSING SPEC"
    match = STATUS_RE.search(spec_path.read_text(encoding="utf-8"))
    return match.group(1).strip() if match else "UNDECLARED"


def inventory(specs_root: pathlib.Path) -> list[FeatureInventory]:
    if not specs_root.is_dir():
        raise ValueError(f"specs root does not exist: {specs_root}")

    items: list[FeatureInventory] = []
    for feature_dir in sorted(path for path in specs_root.iterdir() if path.is_dir()):
        spec = feature_dir / "spec.md"
        plan = feature_dir / "plan.md"
        tasks = feature_dir / "tasks.json"
        if not any(path.exists() for path in (spec, plan, tasks)):
            continue
        items.append(
            FeatureInventory(
                feature=feature_dir.name,
                status=declared_status(spec),
                has_spec=spec.is_file(),
                has_plan=plan.is_file(),
                has_tasks=tasks.is_file(),
            )
        )
    return items


def render_markdown(specs_root: pathlib.Path) -> str:
    rows = inventory(specs_root)
    lines = [
        "# Specification inventory",
        "",
        "> Generated by `tooling/agent-harness/spec_inventory.py`. Do not edit by hand.",
        "> `harness.py validate-all` executes only entries with `tasks.json`; document-only",
        "> entries remain visible here so absence of executable tasks cannot be mistaken for PASS.",
        "",
        "| Feature | Declared status | spec.md | plan.md | tasks.json | Harness mode | validate-all |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{item.feature}`",
                    item.status.replace("|", "\\|"),
                    "yes" if item.has_spec else "no",
                    "yes" if item.has_plan else "no",
                    "yes" if item.has_tasks else "no",
                    item.harness_mode,
                    item.validate_all,
                ]
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Policy",
            "",
            "- A directory with `tasks.json` is executable by the repo-native harness and must pass `validate-all`.",
            "- A directory without `tasks.json` is document-only. Its absence from `validate-all` is not a verification result.",
            "- Do not create retroactive tasks or RED evidence solely to make historical work look harness-executed.",
            "- When spec status, plan/tasks presence, or execution mode changes, regenerate this inventory in the same change.",
            "",
        ]
    )
    return "\n".join(lines)


def check(expected_path: pathlib.Path, rendered: str) -> int:
    if not expected_path.is_file():
        print(f"ERROR: specification inventory is missing: {expected_path}", file=sys.stderr)
        return 1
    current = expected_path.read_text(encoding="utf-8")
    if current == rendered:
        print(f"PASS: specification inventory is current: {expected_path}")
        return 0
    print(f"ERROR: specification inventory drifted: {expected_path}", file=sys.stderr)
    for line in difflib.unified_diff(
        current.splitlines(),
        rendered.splitlines(),
        fromfile=str(expected_path),
        tofile="generated",
        lineterm="",
    ):
        print(line, file=sys.stderr)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("specs_root", type=pathlib.Path)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", type=pathlib.Path)
    action.add_argument("--check", type=pathlib.Path)
    args = parser.parse_args()

    try:
        rendered = render_markdown(args.specs_root)
    except (OSError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if args.write is not None:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(rendered, encoding="utf-8")
        print(f"WROTE {args.write}")
        return 0
    return check(args.check, rendered)


if __name__ == "__main__":
    raise SystemExit(main())
